// src/App.vue
<script setup lang="ts">
import Navbar from './components/layout/Navbar.vue'
</script>

<template>
  <div class="app-root min-h-screen bg-[#0b0e14] text-slate-100 flex flex-col font-sans selection:bg-amber-500 selection:text-slate-950">
    <!-- NAVBAR -->
    <Navbar />

    <!-- MAIN VIEW ROUTER CONTENT -->
    <main class="flex-grow">
      <router-view />
    </main>

    <!-- TACTICAL FOOTER -->
    <footer class="mt-auto border-t border-slate-900 bg-slate-950/80 py-6 text-xs text-slate-500">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-3">
        <div class="flex items-center gap-2">
          <span class="w-2 h-2 rounded-full bg-emerald-500"></span>
          <span class="font-mono text-[11px] text-slate-400">CS2 Stratbook v2.0 // Self-Hosted Portainer Build</span>
        </div>
        <div class="flex items-center gap-4 text-[11px]">
          <span>Proxmox LXC Ready</span>
          <span>•</span>
          <span>CS2 Subtick Calibrated</span>
          <span>•</span>
          <span>Offline & Cloud Capable</span>
        </div>
      </div>
    </footer>
  </div>
</template>

// frontend/src/App.jsx
import { useEffect, useState } from 'react';
import { io } from 'socket.io-client';

const socket = io('http://localhost:5000');

export default function App() {
  const [status, setStatus] = useState('Connecting to real-time server...');

  useEffect(() => {
    socket.on('connect', () => {
      setStatus('Connected to real-time sync server!');
    });
    socket.on('disconnect', () => {
      setStatus('Disconnected from server.');
    });
  }, []);

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 p-8 flex flex-col items-center justify-center">
      <h1 className="text-3xl font-extrabold text-orange-500 mb-4">CS2 Stratbook & Tactics</h1>
      <p className="bg-slate-800 border border-slate-700 px-4 py-2 rounded-lg text-emerald-400 font-mono">
        {status}
      </p>
    </div>
  );
}
